# Generated by Django 3.2.8 on 2021-10-05 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='activa', max_length=8)),
                ('ID', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
