# Generated by Django 3.2.8 on 2021-10-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_companies_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('ID', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('status_transaction', models.CharField(max_length=8)),
                ('status_approved', models.BooleanField()),
                ('final_pay', models.CharField(max_length=1)),
                ('ID_Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
            ],
        ),
    ]
